repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: uvx ruff check --fix
        language: system
        types: [python]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: uvx ruff format
        language: system
        types: [python]
        require_serial: true